name: macos-build

# This currently doesn't *seem* to work.
# For some reason the binary is much tinier than Linux/Windows. (70 KB, is that real??)
# Also standard and the cmd_allowed variant have the same checksum,
# meaning they are the same binary. Which makes no sense.
# Unfortunately I can't test the binary itself since I don't own any macOS devices.

on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "persist-cross-job"
    - name: Do the stuff
      shell: bash
      run: |
        mkdir -p artifacts
        cargo build --release
        mv target/release/kanata artifacts/kanata_macos
        cargo build --release --features cmd
        mv target/release/kanata artifacts/kanata_macos_cmd_allowed
    - uses: actions/upload-artifact@v3
      with:
        name: macos-binaries
        path: |
          artifacts/kanata_macos
          artifacts/kanata_macos_cmd_allowed
